### ISSUE TITLE
README links to old web site

### ISSUE THREAD

**Issue by ryandesign** [mhagger/cvs2svn#14]
README hasn't been modified in 18 years and still links to http://cvs2svn.tigris.org/cvs2svn.html which no longer exists.

**Comment by mhagger** [comment]
That's a fair point. https://github.com/mhagger/cvs2svn/pull/16 should fix it, I think. Please let me know if you see any problems in that PR.

**Comment by dsahlberg-apache-org** [comment]
Changes in #16 LGTM, this issue can probably be closed.

Slightly off-topic, I've updated https://www.openhub.net/p/cvs2svn to point to the github site.
