### ISSUE TITLE
There are no tags or releases in this repo

### ISSUE THREAD

**Issue by ryandesign** [mhagger/cvs2svn#15]
There are no git tags or GitHub releases in this repo. I would expect to see a tag for each version mentioned in the CHANGES file and an attached GitHub release offering the original tarball for that version (at least for the most recent version).

**Comment by mhagger** [comment]
Good point. I never uploaded the tags from tigris.org.

I have just done so, and created releases 2.4.0 and 2.5.0. I didn't bother to create archive files, since GitHub does that automatically. I didn't bother to create older releases, because I can hardly imagine anybody wanting them (but the tags are there now, so people can create their own archives if they really want to).

**Comment by ryandesign** [comment]
Thanks!

Note that the automatically-generated GitHub archives are not a substitute for providing your original tarballs when the project has generated files like configure scripts (which does not apply to cvs2svn as far as I know) or when providing historical releases (which does apply here).

There are differences, for example, between what you currently advertise as 2.5.0 ("1") and what you originally shipped as 2.5.0 ("0"), most significantly apparently that cvs2hg was not shipped in 2.5.0 yet it is part of your 2.5.0 tag. Are you sure you tagged the right revision for 2.5.0 or do you know of another reason for the cvs2hg discrepancy?

```
$ diff -ru 0/cvs2svn-2.5.0 1/cvs2svn-2.5.0
Only in 1/cvs2svn-2.5.0: .gitignore
Only in 0/cvs2svn-2.5.0: PKG-INFO
Only in 1/cvs2svn-2.5.0: cvs2hg
Only in 1/cvs2svn-2.5.0/cvs2svn_lib: Makefile
Only in 1/cvs2svn-2.5.0/cvs2svn_lib: test
Only in 1/cvs2svn-2.5.0/cvs2svn_rcsparse: LICENSE.html
Only in 1/cvs2svn-2.5.0/cvs2svn_rcsparse: README.cvs2svn
Only in 1/cvs2svn-2.5.0/cvs2svn_rcsparse: UPSTREAM_SOURCE
Only in 1/cvs2svn-2.5.0/cvs2svn_rcsparse: test-data
Only in 1/cvs2svn-2.5.0/cvs2svn_rcsparse: update
Only in 0/cvs2svn-2.5.0/svntest: err.py
```

Though fewer, there are still differences between the old and new 2.4.0.

```
$ diff -ru 0/cvs2svn-2.4.0 1/cvs2svn-2.4.0
Only in 1/cvs2svn-2.4.0: .gitignore
Only in 0/cvs2svn-2.4.0: PKG-INFO
Only in 1/cvs2svn-2.4.0: cvs2hg
Only in 1/cvs2svn-2.4.0/cvs2svn_lib: Makefile
Only in 1/cvs2svn-2.4.0/cvs2svn_lib: test
Only in 1/cvs2svn-2.4.0/cvs2svn_rcsparse: LICENSE.html
Only in 1/cvs2svn-2.4.0/cvs2svn_rcsparse: README.cvs2svn
Only in 1/cvs2svn-2.4.0/cvs2svn_rcsparse: UPSTREAM_SOURCE
Only in 1/cvs2svn-2.4.0/cvs2svn_rcsparse: test-data
Only in 1/cvs2svn-2.4.0/cvs2svn_rcsparse: update
```

The checksums of the tarballs of course also are different from what was originally released. It is a common desire to wish to verify via checksums that a tarball is the same as a previously released one.

Due to the unusual structure of the tigris web service, archive.org does not appear to have been able to archive the original cvs2svn tarballs. If you don't have copies of them elsewhere that you can upload, you can use the copies that MacPorts saved:

https://distfiles.macports.org/cvs2svn/

The timestamps of those tarballs are not the original timestamps but the timestamps of when the files were mirrored.

**Comment by mhagger** [comment]
I found my original tarballs and the corresponding signature files for those releases, and just uploaded them to GitHub.

The original releases were made using `setup.py`, which doesn't include everything and adds the `PKG-INFO` file. As I recall, `cvs2hg` had a separate repo that was more advanced than the copy in the cvs2svn repo, which is probably why we didn't include it in the releases.

Hope that helps!

**Comment by ryandesign** [comment]
Super! Thanks.
