### ISSUE TITLE
Importing autors names and contrubution maps

### ISSUE THREAD

**Issue by orynider** [mhagger/cvs2svn#24]
It is possible to import autor names and contribution maps from HDD or CD Backup?
-
The project name here is github.com/Mx-Publisher/mxpcms
-
The old project to rsync was pserver:anonymous@mxbb.cvs.sourceforge.net:/cvsroot/mxbb but they did not had users at github so now only works from a CD backup.
-
The new project name would be there git.code.sf.net/p/mxpcms/git  

-
10x

**Comment by ossilator** [comment]
fixing a repo post-conversion requires a git .mailmap, and can be made permanent with git filter-repo (at the cost of invalidating all sha1s). this doesn't have anything to do with cvs2git as such.

if you want to convert from scratch and are asking whether cvs2git accepts a mailmap as input, then check the documentation (i plain don't know).

neither of this has anything to do with backups. you're just confusing the matter.
