### ISSUE TITLE
The repo is not compatible with Windows

### ISSUE THREAD

**Issue by Vertigo093i** [mhagger/cvs2svn#25]
There are at least 2 files with invalid filenames according to Windows filesystem.
Partial workaround is here: https://stackoverflow.com/a/63742773/393672.
But then it produces:

    $ git checkout
    D       "test-data/main-cvsrepos/single-files/\"double-double-quotes\",v"
    D       "test-data/main-cvsrepos/single-files/single-double-quote\",v"

**Comment by mhagger** [comment]
This project is long since in maintenance mode. The files that you mention are only needed for the automated tests, not for actually running conversions. → WONTFIX.
